### ISSUE TITLE
Can't reproduce

### ISSUE THREAD

**Issue by wuyuwangqingtian** [Shua-Kang/ros_pytorch_yolov5#1]
Hello, I used your project, but there is no picture. Can you tell me more specifically? Thank you for your help. If you can, you can communicate via email. My email is 2541263422@qq.com

**Comment by Shua-Kang** [comment]
Do you mean watching image with bounding box using Rviz? I didn't implement this function now. I will make it in three weeks. Currently it can only get bounding box data.

**Comment by wuyuwangqingtian** [comment]
> Do you mean watching image with bounding box using Rviz? I didn't implement this function now. I will make it in three weeks. Currently it can only get bounding box data.

thank you for your reply

**Comment by Shua-Kang** [comment]
Set view_img=True to track detection. No need for Rviz now.
