### ISSUE TITLE
Color problem of detection results

### ISSUE THREAD

**Issue by 646145192** [Shua-Kang/ros_pytorch_yolov5#12]
Hi!
When I run your program, the wrong color appears. Do you know the reason? The rgb information of the camera looks correct in rviz, but the color is reversed in yolo. I am using a realsense D455 camera.
Looking forward to your reply！
![2022-06-20 17-19-44 的屏幕截图](https://user-images.githubusercontent.com/74187736/174569815-c09a8c65-6ed3-4b33-ba64-c54154fa7aec.png)

**Comment by Shua-Kang** [comment]
It is because the detect.py thinks the image received is BGR format. So, at detect.py line 264
```python
img = img[:, :, ::-1].transpose(2, 0, 1)  # BGR to RGB, to 3x416x416
```
it will convert the image to RGB format for inference.

And when publishing, it will publish BGR version.(line 349)
```python
img_msg = self.bridge.cv2_to_imgmsg(im0, encoding="bgr8")
```
Try to modify line 264 to img = ~~img[:, :, ::-1]~~ img.transpose(2, 0, 1) and modify line 349 to "rgb8" and I think you can get the right color.

**Comment by 646145192** [comment]
I tried your method but the following problem occurred
![2022-06-20 21-20-09 的屏幕截图](https://user-images.githubusercontent.com/74187736/174611032-f8a96284-ef42-471f-9801-374ba8d4b8a7.png)
If I change line 264 
`img = img.transpose(2, 0, 1)`
and change line 349
`img_msg = self.bridge.cv2_to_imgmsg(im0, encoding="rgb8")`
It works fine but the color issue persists

**Comment by Shua-Kang** [comment]
~~line 264 should be~~
```python
img = img[:, :, ::-1]
```
~~.transpose(2,0,1) is used for covert bgr to rgb.~~

**Comment by 646145192** [comment]
if i use
`img = img[:, :, ::-1]`
as line 264
error persists
![image](https://user-images.githubusercontent.com/74187736/174616989-53a826c3-960f-45c0-bb85-b4b3e42aad8e.png)
It seems that the image is not the right size without transpose

**Comment by Shua-Kang** [comment]
You are right and I made a mistake. [:, :, ::-1] is used for covert bgr to rgb and transpose is for the right shape.
Add code before line 349 to see if rviz have any changes.
```python
im0 = im0[:, :, ::-1]
img_msg = self.bridge.cv2_to_imgmsg(im0, encoding="rgb8")
```

**Comment by 646145192** [comment]
it's still the wrong color...
whether i use `img = img[:, :, ::-1].transpose(2, 0, 1)` or `img = img.transpose(2, 0, 1)` in line 264
and I have add `im0 = im0[:, :, ::-1]`before 349

**Comment by Shua-Kang** [comment]
This is too weird. Did the topic you watch is /detections_image ?

**Comment by 646145192** [comment]
not exactly the same as yours

**Comment by Shua-Kang** [comment]
:joy: I will have a test tomorrow.

**Comment by 646145192** [comment]
ok thank you very much

**Comment by Shua-Kang** [comment]
I have updated the repo. I think it is right now. Just have a try
![Snipaste_2022-06-20_23-35-29](https://user-images.githubusercontent.com/40050624/174636764-a4b028e1-5162-4bba-a28d-3d98075f0281.png)
!

**Comment by 646145192** [comment]
Now the color is normal,thank you very much!
