### ISSUE TITLE
请问如何使用自己训练的权重

### ISSUE THREAD

**Issue by 1solati0n** [Shua-Kang/ros_pytorch_yolov5#14]
你好，我想使用自己训练的权重来进行识别，但是我不知道都需要修改哪些地方，请问该怎么去修改呢

**Comment by Shua-Kang** [comment]
I think you can try:
  1. put your model file to ros_pytorch_yolov5/yolov5/weights
  2. modify line 3 of [ros_pytorch_yolov5/launch/detector.launch] to your model file name.

**Comment by 1solati0n** [comment]
I tried but yolo.py have a lot of errors ,I tried to solve one by one and now it works successfully

**Comment by Shua-Kang** [comment]
OK. Maybe it is because different yolo versions have different yolo.py.
