### ISSUE TITLE
博主提供demo的bag么。。。

### ISSUE THREAD

**Issue by shadfien** [Shua-Kang/ros_pytorch_yolov5#2]
cd src/ros_pytorch_yolov5/bag_dataset
运行到这一步发现没有bag，尴尬了呀

**Comment by Shua-Kang** [comment]
I've been too busy lately, so I haven't put together a bag file to upload. But there is one available now, so if you need it, email  (jiuerrose@outlook.com) me to send it to you.

**Comment by shadfien** [comment]
> I've been too busy lately, so I haven't put together a bag file to upload. But there is one available now, so if you need it, email ([jiuerrose@outlook.com](mailto:jiuerrose@outlook.com)) me to send it to you.

Hello blogger, thank you for your advice. I found a usable bag file myself. After running the bag, is there a detection box for displaying the image on rviz? I don't have one. Or do you need other commands to output detection information.

**Comment by Shua-Kang** [comment]
> > I've been too busy lately, so I haven't put together a bag file to upload. But there is one available now, so if you need it, email ([jiuerrose@outlook.com](mailto:jiuerrose@outlook.com)) me to send it to you.
> 
> Hello blogger, thank you for your advice. I found a usable bag file myself. After running the bag, is there a detection box for displaying the image on rviz? I don't have one. Or do you need other commands to output detection information.

I've been too busy lately so I don't have time to write the rviz module for now. For now it is going to print detection information on the command line. Default image topic is /cam0/image_raw. Check if it is match your bag file.

**Comment by Shua-Kang** [comment]
Added demo .bag file at how_to_build_and_run.md.
