### ISSUE TITLE
I can run yolov5s.pt but if I want to change weights I take this error 

### ISSUE THREAD

**Issue by hasantokatlioglu** [Shua-Kang/ros_pytorch_yolov5#5]
![error](https://user-images.githubusercontent.com/93164887/155600550-5d772b17-9cb8-45b1-b7b1-ecd2de1e4bf1.png)

**Comment by Shua-Kang** [comment]
This repository uses v5.0 version of yolov5, you may be using the latest 6.1 or other versions.
Two ways
1. Use yolov5 v5.0 to train your model. Find v5.0 version from release. https://github.com/ultralytics/yolov5/releases
2. Update yolov5 of this repo to the version you are using.

**Comment by hasantokatlioglu** [comment]
How can I apply second method ?

**Comment by hasantokatlioglu** [comment]
when I was training, I used yolov5x.pt

**Comment by Shua-Kang** [comment]
It needs to replace the file from yolov5 of this repo. From your screenshot, I think you can try to replace ros_pytorch_yolov5/yolov5/models/common.py with your_yolov5/models/common.py. And after replacement, if it gets new error from other files, just replace them with yours.

**Comment by hasantokatlioglu** [comment]
Thank you

**Comment by Shua-Kang** [comment]
@hasantokatlioglu 
Yolov5 v6.1 has been updated at branch v6.1. https://github.com/Shua-Kang/ros_pytorch_yolov5/tree/v6.1
