### ISSUE TITLE
Problems with changing the weights file 

### ISSUE THREAD

**Issue by 646145192** [Shua-Kang/ros_pytorch_yolov5#6]
I have seen your previous reply to another questioner ，And I got this error after changing the common.py file when I was operating .If it is convenient for you, I don't know if you can make a tutorial for changing the weight of YOLOV5 v6.1 .I don't know how to proceed at the moment .Thanks for reading and looking forward to your recovery .
![image](https://user-images.githubusercontent.com/74187736/157189516-b9c7e91d-423b-4d86-aa83-af344d9aa600.png)

**Comment by Shua-Kang** [comment]
I'd like to help you, but I've been very busy recently. I think you can try to replace every file that is wrong. From your log we can see that yolo.py is incompatible after replacing common.py, at this point you can choose the latest yolo.py to replace it. The same is true for any other incompatibilities that may occur. If it still doesn't work in the end, I think it might 2-3 weeks before I have time to fix the problem.

**Comment by 646145192** [comment]
Thank you for your reply, I hope that when it is convenient for you, you can see your tutorial and learn your methods and ideas

**Comment by 646145192** [comment]
Sorry to bother you, but do you have time to solve the migration problem of version 6.1?

**Comment by Shua-Kang** [comment]
> Sorry to bother you, but do you have time to solve the migration problem of version 6.1?

Sorry that I am too busy these days. I will try to do it this weekend.

**Comment by Shua-Kang** [comment]
v6.1 has been updated. Just try it!  @646145192 
https://github.com/Shua-Kang/ros_pytorch_yolov5/tree/v6.1

**Comment by 646145192** [comment]
Thank you so much for everything you do, it really helps

**Comment by 646145192** [comment]
Thank you so much for everything you do, it really helps
