### ISSUE TITLE
thanks for you effort,and could you give us the python file for BoundingBox plz?

### ISSUE THREAD

**Issue by panzerjagerWang** [Shua-Kang/ros_pytorch_yolov5#9]
i will really appreciate that , cz it rings:    
from ros_pytorch_yolov5.msg import BoundingBox, BoundingBoxes
ModuleNotFoundError: No module named 'ros_pytorch_yolov5'

**Comment by Shua-Kang** [comment]
I think you forgot to source the devel/setup.bash file.

**Comment by panzerjagerWang** [comment]
mate, you must be a genius, that problem have troubled me for ages,thx

**Comment by Shua-Kang** [comment]
:D
